#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import sys
from contextlib import redirect_stdout
from dataclasses import dataclass
from io import StringIO
from pathlib import Path

from measure import build_graph


@dataclass(frozen=True)
class CouplingMetric:
    fan_out: int
    instability: float


def load_metrics(path: Path) -> dict[str, CouplingMetric]:
    metrics: dict[str, CouplingMetric] = {}

    with path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        required = {"Module", "Fan-Out", "Instability"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            names = ", ".join(sorted(missing))
            raise ValueError(f"Missing CSV columns: {names}")

        for row in reader:
            module = row["Module"].strip()
            if not module:
                continue
            if module in metrics:
                raise ValueError(f"Duplicate module in CSV: {module}")

            metrics[module] = CouplingMetric(
                fan_out=int(row["Fan-Out"]),
                instability=float(row["Instability"]),
            )

    return metrics


def write_report(
    project: Path,
    metrics: dict[str, CouplingMetric],
    output: Path,
) -> None:
    with redirect_stdout(StringIO()):
        graph = build_graph(project)
    known_modules = set(metrics)

    with output.open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow(
            [
                "module",
                "module-Instability",
                "dependency",
                "dependency-Instability",
            ]
        )

        for source in sorted(known_modules):
            if source not in graph.modules:
                raise ValueError(f"CSV module not found in project: {source}")

            targets = sorted(
                target
                for target in graph.edges.get(source, set())
                if target in known_modules
            )
            metric = metrics[source]

            if len(targets) != metric.fan_out:
                raise ValueError(
                    f"Stale CSV for {source}: CSV Fan-Out={metric.fan_out}, "
                    f"current Fan-Out={len(targets)}"
                )

            for target in targets:
                target_instability = metrics[target].instability
                if metric.instability < target_instability:
                    writer.writerow(
                        [
                            source,
                            metric.instability,
                            target,
                            target_instability,
                        ]
                    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Count Stable Dependencies Principle violations per Rust module."
    )
    parser.add_argument("project", help="Rust project directory")
    parser.add_argument(
        "-i",
        "--input",
        default=None,
        help="CSV generated by measure.py",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output CSV",
    )
    args = parser.parse_args()

    project = Path(args.project).resolve()
    input_path = (
        Path(args.input).resolve()
        if args.input
        else project / "module_coupling.csv"
    )
    output_path = (
        Path(args.output).resolve()
        if args.output
        else project / "sdp_violations.csv"
    )

    try:
        metrics = load_metrics(input_path)
        write_report(project, metrics, output_path)
    except (OSError, ValueError, KeyError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1

    print(f"Wrote {output_path}")
    print(f"Modules: {len(metrics)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
